# Generated by Django 4.1.2 on 2023-02-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bundle_id',
            field=models.ForeignKey(db_column='bundle_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='api.bundle'),
            preserve_default=False,
        ),
    ]
