# Generated by Django 4.1.2 on 2023-02-12 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_profile_picture'),
    ]

    operations = [

    ]
