# Generated by Django 4.1.2 on 2023-02-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_paymentmethod_payment_method_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('account_id', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('token', models.CharField(max_length=128)),
                ('expire_timestamp', models.IntegerField()),
            ],
        ),
    ]
