# Generated by Django 4.1.2 on 2023-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_accounttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='expire_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounttoken',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
